### ISSUE TITLE
integrate metric endpoint used for monitoring system

### ISSUE THREAD

**Issue by minderjan** [muuvy/muuvy-backend#8]
### Customer value
as a developer I need metric values of the health state. this is needed to setup an automatic alerting system on system errors. 

### Acceptance criteria
- an endpoint on `/health` which returns a list of metrics (prometheus or other format) which can be integrated in a monitoring database

### Comment
- [Throntail Metrics] https://docs.thorntail.io/2.4.0.Final/#application-metrics_thorntail
- [What is Prometheus?] https://prometheus.io/
- [Setup an Local Environment] https://www.kodnito.com/posts/getting-started-with-microprofile-metrics-and-prometheus/

**Comment by xXx-DoMoDo-xXx** [comment]
- pom.xml extended with
```
        <dependency>
            <groupId>io.thorntail</groupId>
            <artifactId>microprofile-metrics</artifactId>
        </dependency>
```

- create a new class "MetricController"
- copy the template from https://www.kodnito.com/posts/getting-started-with-microprofile-metrics-and-prometheus/ and a little bit customizing, see here: https://github.com/muuvy/muuvy-backend
- install postman (for check the POST/GET etc.)
- extract the zip of prometheus, which you have downloaded before: https://prometheus.io/download/ (you can download it with linux, with wget function and tar)
- inside the extracted file, customize the prometheus.yml:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'thorntail'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:8080']

```
- call prometheus with browser: localhost:9090
